Catalog screen implementation
DmnUAll/iOS-FakeNFT-StarterProject-Public pull request #58
Opened 2023-07-03 13:37 UTC by KirillShakurov

Catalog Screen UI and Logic have been implemented

Project architecture: MVVM

Link to the workflow dashboard:
https://github.com/users/DmnUAll/projects/6

2023-07-04 10:24 UTC, IBDesignable reviewed
Нужно доработать проект:
- поправить ошибки верстки
- поправить байдинг/направление запросов к вьюмодели 
- докрутить избранное/корзину, чтобы сохранялся стейт
- обработать сетевые ошибки 

Все дальнейшие работы: доработка эпика и новые фичи ннужно будет подливать в этот ПР. 
При сдаче спринта номер 20 убедись, что твоя работа удовлетворяет всем базовым критериям, чтобы сразу получить апрув на мердж с командой!

2023-07-04 10:24 UTC, IBDesignable commented on Decomposition/catalog_plan.md
> +
Здесь супер – все задачи с глагола, очень конкретные и понятные. Время и отметки о затраченном есть 

Круче еще собрать в итоге суммарно сколько ушло на эпик

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTLIstViewModel.swift
> +    func sortItems(by category: SortingCategory, _ items: @escaping ([NFTCollectionModel]) -> Void)
С точки зрения MVVM направление запросов неверное. Вью как будто бы собирается давать команды своей вью модели. А это не так, она должна рассказывать о событиях произошедших на экране. 

Запрашивать что-то и задавать категорию сортировки - не ок. 
Сообщать что нажата кнопка сортировки, или что экран загрузился, или что выбрана какой-то элемент (не cell, а элемент! ячейка - это конкретная реализация вью слоя, вьюмодели про него можно не знать). 

Это нужно поправить чтобы закрыть критерий по архитектуре

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTLIstViewModel.swift
> +                print(error)
при ошибке тоже стоит выходить из группы и принимать решение можно ли двигаться дальше, если тут зафейлились. 

Аналогично и ниже. 

Обрати внимание, что просто принт с ошибкой не закрывает критерий по работе с сетевым запросами: здесь нужно обработать ошибку с точки зрения логики приложения и/или макета

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTLIstViewModel.swift
> +                self.nftCollectionItems = data
обращаешься с self без ослабления ссылки – будут утечки памяти

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListFactory.swift
> +    }
Очень круто что есть фабрика для экрана. Я бы ушла от статических функций – чем меньше их, чем меньше паттерна синглтона, тем сильнее выглядит работа

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListViewController.swift
> +    }
Такой подход с комлпишеном в ините выглядит не красиво (ок если на всем проекте будете так использовать), но помоему опыту здесь очень легко спутать с таким паттерном:

```swift 
lazy var view: UIView = {
    return UIView() // тут может быть более сложная настройка. 
}()
```

Поэтому я бы предложила разнести инициализацию и настройку байдинга в разные места:
1) инициализация тупенькая NFTListContainerView()
2) на момент загрузки viewDidLoad настроить байдинг через свойство

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListViewController.swift
> +        container.configure(configuration: .loading)
очень хорошо что настройка поделена на разные шаги функции

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListViewController.swift
> +        configureNavigationController()
а тут дубль, похоже надо удалить

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListViewController.swift
> +        present(alertController, animated: true)
UIAlertController - тоже экран, его стоит описывать в рамках архитектуры MVVM

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListFactory.swift
> +    }
Можно оставить как есть

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/View/NFTListCell.swift
> +    var decodeUrl: String {
Неконсистентно, выше такие же замыкания разбиваешь пропусками
```suggestion
    }
    
    var decodeUrl: String {
```

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/View/NFTListCell.swift
> +        return self.addingPercentEncoding(withAllowedCharacters: NSCharacterSet.urlQueryAllowed)!
можно опускать return в однострочных  computed свойствах

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/View/NFTLoadingView.swift
> +    private func _setupSubviews() {
почему вдруг синтаксис с нижнего подчеркивания?

это не swifty-way, давай уберем. 

Такой подход можно встретить в питоне или в objc, но мы же пишем на swift, поэтому давай не будем мешать.

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/NFTDetailsViewController.swift
> +                self.viewModel.addTofavouriteNft(index: index)
отступ уехал.

тут вижу что опять байдинг в инитие, в целом можно оставить, при условии что вся команда будет использвать этот же подход.

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/NFTDetailsViewController.swift
> +    }
ну такое мы на ревью не оставляем

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/NFTDetailsViewController.swift
> +    }
не используется, нужно удалить. Либо, если этот код будет дописан, принято оставлять комментарии-TODO, чтобы коллега на ревью лишний раз не обращал внимание на такие вещи

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/NFTDetailsViewModel.swift
> +    func selectNft(index: Int)
глагол "выбрать", а нужно "выбрано" 

Это повторное замечание про направление запросов от View к ViewModel

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDescriptionCollectionViewCell.swift
> +        stackView.translatesAutoresizingMaskIntoConstraints = false
👀

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDescriptionCollectionViewCell.swift
> +class NFTDescriptionCollectionViewCell: UICollectionViewCell {
судя по всему ты обычно используешь final, возможно тут пропустил

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDescriptionCollectionViewCell.swift
> +        stackView.setCustomSpacing(8, after: sectionNameLabel)
а почему один раз не установить спейсинг? не очевидно из кода

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDetailsCollectionViewCell.swift
> +        }
здесь что-то странное происходит: 
1) вьюшка почему-то начинает думать, и какие-то условия проверять. Это все называется логикой и ее надо отдать либо холдеру (родительской вьюмодели) либо завести вьюмодель для ячейки (ячейки и сабвью могут быть тоже самостоятельными MVVM модулями)
2) сравнение с объектом рефференс типа (UIImage) похоже на ошибку и ты удачлив, если это работает) 
Вообще конечно, лучше завести свойства типа енам со описанным стейтом и отправлять текущее значение, а не определять его на ходу

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDetailsCollectionViewCell.swift
> +        }
аналогичное замечание

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDetailsContainerView.swift
> +//         layout.minimumInteritemSpacing = 4
давай такое подчистим

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDetailsContainerView.swift
> +        3
какое-то магическое число. 

В идеале, у тебя должны быть запрототипированы секции, или массив с моделями, определяющий количество этих секций. 3 – это не понятное число

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDetailsContainerView.swift
> +
функция получилась длинной, рекомендую разбить на подфункции

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/View/NFTListView.swift
> +    }
1) Пока табличка грузится у нее видны полоски, их также видно при подгрузке картинок и в конце таблицы. Полосок у таблиц в дизайне нет, надо убрать
<img width="458" alt="Снимок экрана 2023-07-04 в 13 08 23" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/4f512106-be27-476a-8b2b-6baf08a5af12">

2) текст должен быть 17 Bold 

<img width="888" alt="Снимок экрана 2023-07-04 в 13 06 37" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/d744343b-5a80-43d9-a5f3-e49268dcbd0e">

3) у таблицы не задан отступ от верхнего края, в макете 20 пунктов 
<img width="458" alt="Снимок экрана 2023-07-04 в 13 01 16" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/94ea9ed5-42d6-47ff-a214-277da815d8d9">

4) перепроверь еще кнопку сортировки, должна быть 42 на 42, а не 42 на 44

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDetailsContainerView.swift
> +    init(details: NFTDetails, cellSelected: @escaping (Action) -> Void) {
Этот экран надо хорошо доработать:  
<img width="458" alt="Снимок экрана 2023-07-04 в 13 08 35" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/0516f301-f527-46a8-9a82-407a128f7649">
<img width="346" alt="Снимок экрана 2023-07-04 в 13 11 04" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/2509771b-7ad0-41a3-9a22-5d0e1eff1f3a">

1) в навбаре не должно быть текста, и не должно быть цветной белой полоски. В макете только стрелочка назад
2) ячейки сверстаны некорректно, звездочки плющатся и не того цвета, картинки не квадратные, оступы между элементами на глаз не совпадают в макет. Тут нужно все перепроверить еще раз
3) шапка заголовка тоже выглядит немного кривоватой, как будто не хватает отсутпа между автором и текстом описанием коллекции, а у заголовка наоборот большой отступ от текста. надо все перепроверить

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/View/NFTDetailsContainerView.swift
> +                self.cellSelected(.unselectBasket(index: indexPath.row))
Добавление в корзину и избранное как будто бы пока не рабоатает: после возвращения в коллекцию, стейт у ячеек без изменений. Надо перепроверить

2023-07-04 10:24 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/NFTDetailsViewController.swift
> +                self.present(vc, animated: true)
Внешний вид такого экрана не попадает в дизайн, нужно делать с вебвью
<img width="458" alt="Снимок экрана 2023-07-04 в 13 19 29" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/9edd015d-9445-470d-abec-79dd1669fd6a">

2023-07-05 09:51 UTC, KirillShakurov commented on FakeNFT/Modules/NTFDetails/View/NFTDetailsContainerView.swift
> +                self.cellSelected(.unselectBasket(index: indexPath.row))
Сервис добавления в корзину находится у одногрупника, который пишет эпик корзины. Объединить усилия получится после вливания всех веток в одну. Тогда и заработает все.

2023-07-09 06:22 UTC, IBDesignable commented on FakeNFT/Foundation/Box.swift
> +  // 4
Давай комменты с цифрами удалим, источник оставим

2023-07-09 06:22 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTLIstViewModel.swift
> +        if case let .loaded(nftCollectionItems) = state.value {
если у тебя только одна ветвь получилась, то стоит попробовать переписать на guard case

2023-07-09 06:22 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTLIstViewModel.swift
> +
здесь лишний пропуск строки, обычно не оставляешь его, надо убрать

2023-07-09 06:22 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListViewController.swift
> +        viewModel.viewDidLoad()
такое лучше посылать после байдингов

2023-07-09 06:22 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListViewController.swift
> +                }
DispatchQueue.main.async можно вынести на уровень выше, за свитч, и не придется дублировать

к тому же, кода в комплишене байдинга много – лучше вынести в функцию


```swift 
DispatchQueue.main.async {
 self?.update(from state: NFTListState)
}
```

2023-07-09 06:22 UTC, IBDesignable commented on FakeNFT/Modules/NFTList/NFTListViewController.swift
>              guard let self else { return }
Строчка в комплишене одна – поэтому можно через слабый self обратиться без разыменовывания

2023-07-09 06:22 UTC, IBDesignable commented on FakeNFT/Modules/NTFDetails/NFTDetailsViewModel.swift
> +        : nftstorageService.unselectNft(nfts.value[index])
Так тоже можно, но чаще стараются не использовать тернарник в случаях, где нет необходимости выбирать значения,. То есть в этой ситуации лучше написать полноценный if-else

2023-07-09 07:50 UTC, IBDesignable requested changes
Привет, Кирилл!
Работа не соответствует базовым критериям, мерджить с командой ветку нельзя. Жду на повторном ревью 

[Кирилл Шакуров - Ревью диплома, эпик каталога.pdf](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/files/11994679/-.pdf)

_Приложения к комментариям_ 
6 звездочек разного размера
<img width="458" alt="Снимок экрана 2023-07-09 в 10 47 43" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/0a6506b8-9b0c-4991-b8eb-b27db3864fa7">
проект не компилируется 
<img width="684" alt="Снимок экрана 2023-07-09 в 10 48 27" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/214cb271-2ffe-42c7-8702-af67a04f37af">

2023-07-10 10:31 UTC, KirillShakurov commented
> Привет, Кирилл! Работа не соответствует базовым критериям, мерджить с командой ветку нельзя. Жду на повторном ревью
> 
> [Кирилл Шакуров - Ревью диплома, эпик каталога.pdf](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/files/11994679/-.pdf)
> 
> _Приложения к комментариям_ 6 звездочек разного размера <img alt="Снимок экрана 2023-07-09 в 10 47 43" width="458" src="https://user-images.githubusercontent.com/121577115/252132649-0a6506b8-9b0c-4991-b8eb-b27db3864fa7.png"> проект не компилируется <img alt="Снимок экрана 2023-07-09 в 10 48 27" width="684" src="https://user-images.githubusercontent.com/121577115/252132675-214cb271-2ffe-42c7-8702-af67a04f37af.png">

Добрый день. 
У меня проект компилируется, не понимаю в чем проблема.
9 пункт: Нет макетов с ошибками интернета в фигме, потому не обрабатываются
Остальные ошибки поправил, сейчас загружу.

2023-07-13 06:42 UTC, IBDesignable commented
> 9 пункт: Нет макетов с ошибками интернета в фигме, потому не обрабатываются

Привет! Я уточняю у команды, почему так вышло, что критерий есть, а экранов нет. 
Но критерии считаю приоритетными в оценке работы: от тебя требуется продемонстрировать как ты это понял и применяешь. Поэтому если чего-то не хватает то можно а) спросить у Наставника б) попробовать реализовать что-то простое. В данном случае хватило бы алерта из первого проекта. 

<img width="278" alt="Снимок экрана 2023-07-13 в 09 36 15" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/f330036c-55b6-4b57-b61a-32ad4c9b5b89">

2023-07-13 06:51 UTC, IBDesignable commented
> У меня проект компилируется, не понимаю в чем проблема.

Файл с документацией лежит не в папке проекта, а в Downloads. Путь к файлу в проекте - относительный (верный для твоего проекта). Если склонируешь проект в другую папку – например в ту же Downloads то у тебя тоже комплиироваться не будет

2023-07-13 06:56 UTC, IBDesignable commented
Верстка и баг с шестью зведочками все еще не исправлен. Мерджить ветку все еще нельзя. 

<img width="458" alt="Снимок экрана 2023-07-13 в 09 53 48" src="https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/assets/121577115/56e35140-ee4b-4cb3-acf3-0d382ed77d79">

2023-07-13 07:03 UTC, IBDesignable requested changes

2023-07-13 07:03 UTC, IBDesignable commented on FakeNFT/Models/Business/NFT.swift
> +    }
Как и любой форматтер дат, этот тоже не стоит при каждом обращении к переменной создавать. Крутой практикой будет вынести создание и настройку форматтера в отдельное место, где ты можешь гарантировать что экземпляр будет создан один

2023-07-17 16:02 UTC, merged